version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
    nodejs: "18"

python:
  version: 3.10
  install:
    - requirements: doc/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - dev

sphinx:
  configuration: doc/conf.py
  fail_on_warning: false

formats:
  - pdf
  - epub

subprojects:
  api:
    python:
      version: 3.10

search:
  ranking: {}

# Notification settings
notifications:
  email: false
  slack: {}

# Build limits
limits:
  build:
    timeout: 1800

# Environment variables (if needed)
# env:
#   PYTHONPATH: .
#   ENV: production
